on: [push]

jobs:
  action_job:
    runs-on: ubuntu-latest
    name: test priv. action
    steps:

    - name: pviate action loader
      uses: AnthonyWC/private-action-loader@v3
      with:
        # access token with repo scope to action repo
        pal-repo-token: ${{ secrets.REPO_TOKEN }}
        pal-repo-name: AnthonyWC/ghaction-docker-test
        #pal-action-directory: src/super-secret-nested-action
        who-to-greet: 'Mona Octocat'

    # Use the output from the `hello` step
    - name: Get output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
